### ISSUE TITLE
Warnings in Mojo::Asset::Memory caused by Future::HTTP::Mojo

### ISSUE THREAD

**Issue by pplu** [Corion/future-http#2]
Hi,

   It looks like the way that Future::HTTP::Mojo is calling build_tx causes warnings when using http_head. Can you please take a look at this issue https://github.com/kraih/mojo/issues/1221 (where I initially reported the bug) for details on how to reproduce the issue?

Thanks

**Comment by Corion** [comment]
Thank you for the diagnosis and fix. This has been fixed in #555906 and is on its way to CPAN as 0.09.
